# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: apiservice
#   labels:
#     name: apiservice
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       name: apiservice
#   template:
#     metadata:
#       labels:
#         name: apiservice
#     spec:
#       containers:
#       - name: apiservice
#         image: apiservice
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: apiservice
# spec:
#   type: NodePort
#   ports:
#   - name: http
#     targetPort: 9090
#     nodePort: 9090
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apiservice
spec:
  selector:
    matchLabels:
      app: apiservice
  template:
    metadata:
      labels:
        app: apiservice
    spec:
      serviceAccountName: default
      terminationGracePeriodSeconds: 5
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      containers:
      - name: server
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          privileged: false
          readOnlyRootFilesystem: true
        image: apiservice
        ports:
        - containerPort: 9090
        env:
        - name: PORT
          value: "9090"
        - name: DISABLE_PROFILER
          value: "1"
        readinessProbe:
          grpc:
            port: 9090
        livenessProbe:
          grpc:
            port: 9090
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: apiservice
spec:
  type: NodePort
  selector:
    app: apiservice
  ports:
  - name: grpc
    port: 9090
    targetPort: 9090